/**
 * Challenge bank — 12 questions per difficulty (36 total).
 * Each item: { id, prompt, promptMath?, choices[], correctIndex, solutionMath, solutionText? }
 * choices are plain text (numbers/currency) for readability; solutions use KaTeX.
 */
window.CHALLENGE_BANK = {
  easy: [
    {
      id: "e01",
      prompt: "Simple interest only on principal: I = Pin. For P = $5,000, i = 8% per year, n = 5 years, total interest is:",
      promptMath: String.raw`I = Pin`,
      choices: ["$2,000", "$1,600", "$2,500", "$700"],
      correctIndex: 0,
      solutionMath: String.raw`I = (5000)(0.08)(5) = 2000`,
      solutionText: "Simple interest does not compound: each year’s interest is 0.08·5000 = 400, so over 5 years interest totals 5·400 = 2000.",
    },
    {
      id: "e02",
      prompt: "Compound annually: F = P(1+i)^n. If P = $500, i = 6%, n = 3 years, F is closest to:",
      promptMath: String.raw`F=P(1+i)^n`,
      choices: ["$595.50", "$590.00", "$600.00", "$530.00"],
      correctIndex: 0,
      solutionMath: String.raw`F=500(1.06)^3 \approx 500(1.191016)=595.51`,
      solutionText: "Apply the single-payment compound factor once per year for three years.",
    },
    {
      id: "e03",
      prompt: "Discount a single future receipt: P = F(1+i)^{-n}. To have F = $800 in 4 years at i = 5% compounded annually, deposit now about:",
      promptMath: String.raw`P=F(1+i)^{-n}`,
      choices: ["$658.16", "$640.00", "$680.00", "$800.00"],
      correctIndex: 0,
      solutionMath: String.raw`P=800(1.05)^{-4} \approx 800(0.822702)=658.16`,
      solutionText: "Use the P/F relationship; the factor (P/F,5%,4) is 1/(F/P,5%,4).",
    },
    {
      id: "e04",
      prompt: "Nominal r = 12% compounded monthly: effective annual rate i_a = (1+r/12)^{12}-1 is approximately:",
      promptMath: String.raw`i_a=\left(1+\frac{r}{12}\right)^{12}-1`,
      choices: ["12.68%", "12.00%", "13.50%", "11.88%"],
      correctIndex: 0,
      solutionMath: String.raw`i_a=(1+0.01)^{12}-1 \approx 0.126825`,
      solutionText: "Monthly means m=12; periodic rate is 0.12/12 = 0.01 per month.",
    },
    {
      id: "e05",
      prompt: "Sinking fund style: solve for A given F. Which factor converts F to an end-of-period uniform series A?",
      choices: ["(A/F,i,n)", "(F/A,i,n)", "(P/A,i,n)", "(A/P,i,n)"],
      correctIndex: 0,
      solutionMath: String.raw`A = F(A/F,i,n)=F\cdot\frac{i}{(1+i)^n-1}`,
      solutionText: "(F/A,i,n) finds F from A; its reciprocal structure yields (A/F,i,n) for the reverse.",
    },
    {
      id: "e06",
      prompt: "End-of-period annuity future worth: F = A·[((1+i)^n-1)/i]. With A = $1,000, i = 7%, n = 4, F is closest to:",
      promptMath: String.raw`F=A\left[\frac{(1+i)^n-1}{i}\right]`,
      choices: ["$4,440", "$4,000", "$4,750", "$3,850"],
      correctIndex: 0,
      solutionMath: String.raw`F=1000\cdot\frac{1.07^4-1}{0.07}\approx 1000\cdot 4.4399`,
      solutionText: "This is the uniform-series compound amount factor applied once.",
    },
    {
      id: "e07",
      prompt: "A project at MARR = 10% has NPW = +$300. The usual accept/reject conclusion is:",
      choices: ["Accept (economically attractive at the stated MARR)", "Reject", "Accept only if payback < 2 years", "Cannot decide without IRR"],
      correctIndex: 0,
      solutionMath: String.raw`\mathrm{NPW}(i=\text{MARR})>0 \Rightarrow \text{accept conventional independent project}`,
      solutionText: "Positive NPW means the cash flow stream earns more than the MARR in present-worth terms for the study period used.",
    },
    {
      id: "e08",
      prompt: "Perpetuity (end-of-period): P = A/i. If A = $600 yearly forever and i = 5%, the capitalized present worth is:",
      promptMath: String.raw`P=\frac{A}{i}`,
      choices: ["$12,000", "$600", "$30,000", "$3,000"],
      correctIndex: 0,
      solutionMath: String.raw`P=\frac{600}{0.05}=12000`,
      solutionText: "A perpetual level payment grows without bound in the future, but its present worth is finite when i>0.",
    },
    {
      id: "e09",
      prompt: "Two mutually exclusive alternatives at the same MARR and same study period both have NPW > 0. Choose:",
      choices: ["The alternative with the larger NPW", "The alternative with the smaller NPW", "The shorter-lived alternative always", "Either; NPW cannot rank"],
      correctIndex: 0,
      solutionMath: String.raw`\max \mathrm{NPW}_j \quad \text{subject to feasibility}`,
      solutionText: "With consistent assumptions and a common horizon, NPW ranking selects the economically dominant mutually exclusive option.",
    },
    {
      id: "e10",
      prompt: "Continuous compounding for one year at continuous rate r: F = Pe^{r}. If P = $2,000 and r = 6% (continuous), F is closest to:",
      promptMath: String.raw`F=Pe^{r}`,
      choices: ["$2,123.67", "$2,120.00", "$2,000.00", "$2,600.00"],
      correctIndex: 0,
      solutionMath: String.raw`F=2000e^{0.06}\approx 2000(1.0618365)`,
      solutionText: "This is the continuous analogue to discrete compounding limits as m→∞ (notation may vary by text).",
    },
    {
      id: "e11",
      prompt: "If compounding is quarterly but cash flows occur quarterly too, the interest period rate i per quarter from nominal annual r is:",
      choices: ["r/4", "r", "r/12", "(1+r)^{1/4}-1"],
      correctIndex: 0,
      solutionMath: String.raw`i_{\text{quarter}}=\frac{r}{m},\quad m=4`,
      solutionText: "Align the periodic rate with the cash-flow period before applying factors.",
    },
    {
      id: "e12",
      prompt: "NPW sign rule (single project, conventional flows): NPW < 0 at the MARR implies:",
      choices: ["The project does not meet the MARR as a PW test", "Accept immediately", "MARR must be zero", "NPW is undefined"],
      correctIndex: 0,
      solutionMath: String.raw`\mathrm{NPW}(i=\text{MARR})<0 \Rightarrow \text{reject}`,
      solutionText: "Negative NPW means the discounted net cash flows fall short of recovering capital at the hurdle rate (for the modeled assumptions).",
    },
    {
      id: "e13",
      prompt: "What is the simple interest on $1,000 at 5% per year for 3 years?",
      choices: ["$150", "$115.76", "$1,159.77", "$159.77"],
      correctIndex: 0,
      solutionMath: String.raw`I = Prn = 1000 \times 0.05 \times 3 = 150`,
      solutionText: "Simple interest: I = Prn = 1000 × 0.05 × 3 = $150. No compounding.",
    },
    {
      id: "e14",
      prompt: "If you borrow $5,000 at 8% annual interest and repay $1,000 per year, approximately how many years to pay off?",
      choices: ["6-7 years", "5 years exactly", "8-9 years", "4-5 years"],
      correctIndex: 0,
      solutionMath: String.raw`\text{Approximate: } n \approx \frac{P}{A} \text{ with interest adjustment}`,
      solutionText: "With interest, it takes longer than P/A = 5 years. About 6-7 years at 8%.",
    },
    {
      id: "e15",
      prompt: "The future value of $1,000 in 1 year at 6% compounded semiannually is closest to:",
      choices: ["$1,060.90", "$1,060.00", "$1,061.80", "$1,000.00"],
      correctIndex: 0,
      solutionMath: String.raw`F = 1000(1 + 0.06/2)^2 = 1000(1.03)^2 = 1060.90`,
      solutionText: "Semiannual compounding: 2 periods at 3% each.",
    },
    {
      id: "e16",
      prompt: "A $10,000 loan at 12% annual interest, paid back in 1 year. Total interest with monthly compounding is approximately:",
      choices: ["$1,268.24", "$1,200.00", "$1,100.00", "$1,127.16"],
      correctIndex: 0,
      solutionMath: String.raw`F = 10000(1 + 0.12/12)^{12} - 10000`,
      solutionText: "EAR = 12.68%, so interest ≈ $1,268.",
    },
    {
      id: "e17",
      prompt: "Which of the following is NOT a characteristic of simple interest?",
      choices: ["Interest earns interest", "Interest calculated on principal only", "Linear growth", "Used for short-term loans"],
      correctIndex: 0,
      solutionText: "Simple interest only calculates on the original principal. Compounding earns interest on interest.",
    },
    {
      id: "e18",
      prompt: "For a perpetuity paying $500 per year at i=10%, the present worth is:",
      choices: ["$5,000", "$500", "$5,500", "$10,000"],
      correctIndex: 0,
      solutionMath: String.raw`P = A/i = 500/0.10 = 5000`,
      solutionText: "Perpetuity formula: P = A/i = $500/0.10 = $5,000.",
    },
    {
      id: "e19",
      prompt: "The factor (F/P, 5%, 10) is used to find:",
      choices: ["Future value given present value", "Present value given future value", "Annual value given future value", "Future value given annual value"],
      correctIndex: 0,
      solutionText: "(F/P, i, n) converts a present amount to its future equivalent.",
    },
    {
      id: "e20",
      prompt: "At MARR = 8%, which project should be selected if both are independent?",
      choices: ["Both projects (NPW > 0 for each)", "Only Project A", "Only Project B", "Neither project"],
      correctIndex: 0,
      solutionText: "For independent projects, accept any with NPW > 0 at MARR.",
    },
    // True/False Questions
    {
      id: "ef01",
      type: "truefalse",
      prompt: "Simple interest grows exponentially over time.",
      correctIndex: 1,
      solutionText: "False. Simple interest grows linearly. Only compound interest grows exponentially.",
    },
    {
      id: "ef02",
      type: "truefalse",
      prompt: "The future value of $1,000 at 10% simple interest for 2 years is $1,200.",
      correctIndex: 0,
      solutionMath: String.raw`F = P(1+in) = 1000(1+0.10 \times 2) = 1200`,
      solutionText: "True. Simple interest: I = 1000 × 0.10 × 2 = $200, so F = $1,200.",
    },
    {
      id: "ef03",
      type: "truefalse",
      prompt: "Compounding more frequently always results in higher effective annual rate.",
      correctIndex: 0,
      solutionText: "True. More frequent compounding means interest earns interest sooner, so EAR increases.",
    },
    {
      id: "ef04",
      type: "truefalse",
      prompt: "The present worth of a future amount is always less than the future amount.",
      correctIndex: 0,
      solutionText: "True. At positive interest rates, money today is worth more than the same amount in the future.",
    },
    // Fill in the Blank Questions
    {
      id: "eb01",
      type: "fillblank",
      prompt: "The formula for simple interest is I = _____.",
      correctAnswer: "Prn",
      solutionMath: String.raw`I = Prn`,
      solutionText: "Simple interest = Principal × rate × number of periods.",
    },
    {
      id: "eb02",
      type: "fillblank",
      prompt: "At 5% interest, $1,000 will grow to $1,050 in _____ year(s).",
      correctAnswer: "1",
      solutionMath: String.raw`F = P(1+i) = 1000(1.05) = 1050`,
      solutionText: "One year at 5% simple or annual compound interest.",
    },
    {
      id: "eb03",
      type: "fillblank",
      prompt: "The factor (F/P, 5%, 10) is used to find _____ value.",
      correctAnswer: "future",
      solutionText: "(F/P) finds future value given present value.",
    },
    {
      id: "eb04",
      type: "fillblank",
      prompt: "If MARR = 10% and NPW = $5,000, the project should be _____.",
      correctAnswer: "accepted",
      solutionText: "Accepted. Positive NPW means the project meets or exceeds the MARR.",
    },
  ],
  medium: [
    {
      id: "m01",
      prompt: "Compare borrowing costs: Loan A is 11.8% nominal compounded monthly; Loan B is 12.0% nominal compounded quarterly. Which has the lower effective annual rate (EAR)?",
      choices: ["A (about 12.47% vs 12.55%)", "B", "They are equal", "Cannot compute without principal"],
      correctIndex: 0,
      solutionMath: String.raw`i_{aA}=(1+0.118/12)^{12}-1,\quad i_{aB}=(1+0.12/4)^4-1`,
      solutionText: "Compute each EAR: A ≈ 12.47%, B ≈ 12.55%. Lower EAR is cheaper for borrowing.",
    },
    {
      id: "m02",
      prompt: "Find P for an annuity: P = A(P/A,i,n). With A = $250, i = 8% per year, n = 10, P is closest to (use tables or compute):",
      promptMath: String.raw`P=A(P/A,8\%,10)`,
      choices: ["$1,677.53", "$2,500.00", "$1,200.00", "$3,000.00"],
      correctIndex: 0,
      solutionMath: String.raw`P=250\cdot\frac{1-(1.08)^{-10}}{0.08}\approx 250(6.7101)`,
      solutionText: "The (P/A) factor discounts a level end-of-year series to its present equivalent.",
    },
    {
      id: "m03",
      prompt: "Find A to reach F: A = F(A/F,i,n). To accumulate F = $10,000 in 6 years at i = 6% compounded annually, uniform end-of-year deposits are about:",
      choices: ["$1,433.28", "$1,666.67", "$1,200.00", "$2,000.00"],
      correctIndex: 0,
      solutionMath: String.raw`A=10000\cdot\frac{0.06}{(1.06)^6-1}`,
      solutionText: "This is the sinking-fund factor: spread a future target into equivalent annual set-asides.",
    },
    {
      id: "m04",
      prompt: "Two-year loan effective rate: 12% nominal compounded monthly for a 6-month horizon. The 6-month effective rate is closest to:",
      choices: ["6.15%", "6.00%", "12.00%", "3.00%"],
      correctIndex: 0,
      solutionMath: String.raw`i_{6\text{-mo}}=\left(1+\frac{0.12}{12}\right)^{6}-1`,
      solutionText: "Six monthly periods at 1% per month: (1.01)^6−1 ≈ 6.15% for the half-year.",
    },
    {
      id: "m05",
      prompt: "Given P = $1,000, i = 8% per year, n = 5 annual periods, F = P(F/P,8%,5). F is closest to:",
      choices: ["$1,469.33", "$1,400.00", "$1,800.00", "$1,080.00"],
      correctIndex: 0,
      solutionMath: String.raw`F=1000(1.08)^5 \approx 1469.33`,
      solutionText: "Single-payment compound amount for five annual periods.",
    },
    {
      id: "m06",
      prompt: "If a project’s NPW at MARR is exactly zero, the interpretation is:",
      choices: ["The project returns exactly the MARR in PW terms", "The project loses money for sure", "IRR is undefined", "MARR must be negative"],
      correctIndex: 0,
      solutionMath: String.raw`\mathrm{NPW}(i=i^*)=0 \Rightarrow i^*=\text{IRR for simple cases}`,
      solutionText: "NPW = 0 means the discounted cash flows break even against the hurdle rate used in the analysis.",
    },
    {
      id: "m07",
      prompt: "Different-life machines with repeatability: the study period is often chosen as:",
      choices: ["The LCM of useful lives", "Always 1 year", "The longer life only", "The shorter life only"],
      correctIndex: 0,
      solutionMath: String.raw`n_{\text{study}}=\mathrm{lcm}(n_A,n_B)`,
      solutionText: "Align repeated cycles so each alternative experiences an integer number of replacements over the same horizon.",
    },
    {
      id: "m08",
      prompt: "Arithmetic gradient base+G pattern: the standard tabulated (P/G,i,n) factor applies to a series that begins with:",
      choices: ["0 at period 1, then G,2G,… after converting the base", "A positive cash flow at period 0 only", "Equal amounts forever without base", "Only decreasing series"],
      correctIndex: 0,
      solutionMath: String.raw`P = A(P/A,i,n) \pm G(P/G,i,n)`,
      solutionText: "Textbooks shift the standard gradient form; always match the tabulated convention to your cash-flow timing.",
    },
    {
      id: "m09",
      prompt: "Continuous effective annual rate from continuous nominal r (common textbook form): i_a equals:",
      choices: ["e^{r}-1", "r", "ln(1+r)", "e^{r}"],
      correctIndex: 0,
      solutionMath: String.raw`i_a=e^r-1`,
      solutionText: "This pairs with F = Pe^{rt} for continuous compounding over t years (verify notation in your 11th edition).",
    },
    {
      id: "m10",
      prompt: "You need F = $2,000 in 3 years. Bank pays 3% compounded annually. Deposit today P is about:",
      choices: ["$1,827.07", "$2,000.00", "$1,940.00", "$1,700.00"],
      correctIndex: 0,
      solutionMath: String.raw`P=2000(1.03)^{-3}`,
      solutionText: "Single-payment present worth factor applied once.",
    },
    {
      id: "m11",
      prompt: "For mutually exclusive alternatives with different lives, comparing NPW at each asset’s own life without adjustment generally:",
      choices: ["Can mis-rank unless study periods are aligned", "Is always correct", "Requires IRR only", "Ignores salvage automatically"],
      correctIndex: 0,
      solutionMath: String.raw`\text{Need consistent } n_{\text{study}} \text{ and replacement assumptions}`,
      solutionText: "NPW comparisons must use the same analysis window and consistent reinvestment assumptions.",
    },
    {
      id: "m12",
      prompt: "If compounding is monthly but deposits are end-of-month, the correct periodic i in monthly factors is typically:",
      choices: ["Nominal annual rate divided by 12", "Nominal annual rate", "EAR divided by 12 without checking", "Zero"],
      correctIndex: 0,
      solutionMath: String.raw`i_{\text{month}}=\frac{r}{12}`,
      solutionText: "Match i and n to the month; then use (F/A,i,n) with n in months.",
    },
    {
      id: "m13",
      prompt: "A machine costs $50,000, lasts 5 years, salvage $10,000. At i=10%, EUAC is approximately:",
      choices: ["$12,637", "$10,000", "$8,000", "$15,000"],
      correctIndex: 0,
      solutionMath: String.raw`EUAC = 50000(A/P,10\%,5) - 10000(A/F,10\%,5)`,
      solutionText: "EUAC includes both capital recovery and salvage value effects.",
    },
    {
      id: "m14",
      prompt: "For an arithmetic gradient with A1=$100, G=$50, n=5, the present worth includes:",
      choices: ["A(P/A, i%, n) + G(P/G, i%, n)", "A(P/A, i%, n) only", "G(P/G, i%, n) only", "(A+G)(P/A, i%, n)"],
      correctIndex: 0,
      solutionMath: String.raw`P = A_1(P/A,i,n) + G(P/G,i,n)`,
      solutionText: "The uniform series A1 plus the gradient component G.",
    },
    {
      id: "m15",
      prompt: "Which investment criterion always leads to the same decision as NPW for independent projects?",
      choices: ["NPV > 0 (accept all positive NPV)", "IRR > 0", "Payback < 5 years", "Profitability index > 1"],
      correctIndex: 0,
      solutionMath: String.raw`\text{Accept if } \sum_t \frac{CF_t}{(1+i)^t} > 0`,
      solutionText: "For independent projects, any positive NPV project adds value.",
    },
    {
      id: "m16",
      prompt: "The profitability index (PI) is calculated as:",
      choices: ["PV of inflows / PV of outflows", "NPV / Initial investment", "IRR / MARR", "Future value / Present value"],
      correctIndex: 0,
      solutionMath: String.raw`PI = \frac{\text{PV of inflows}}{\text{PV of outflows}}`,
      solutionText: "PI > 1 means beneficial; PI = 1 means indifferent.",
    },
    {
      id: "m17",
      prompt: "In a geometric gradient series, cash flows grow by a constant percentage g. The present worth formula uses:",
      choices: ["(1+g)/(1+i)", "1/(1+i)", "g/(1+i)", "i/(1+g)"],
      correctIndex: 0,
      solutionMath: String.raw`P = A_1 \frac{1 - ((1+g)/(1+i))^n}{i-g}`,
      solutionText: "This is the geometric gradient present worth factor.",
    },
    {
      id: "m18",
      prompt: "A bond pays $1,000 at maturity (10 years) and $50 coupon annually. At i=6%, price is approximately:",
      choices: ["$926", "$1,000", "$850", "$1,080"],
      correctIndex: 0,
      solutionMath: String.raw`P = 50(P/A,6\%,10) + 1000(P/F,6\%,10)`,
      solutionText: "Bond pricing: PV of coupons plus PV of face value.",
    },
    {
      id: "m19",
      prompt: "When using B/C ratio for project evaluation, a project is acceptable if B/C is:",
      choices: ["> 1.0", "< 1.0", "= 1.0", "> 0"],
      correctIndex: 0,
      solutionMath: String.raw`B/C = \frac{\text{Benefits}}{\text{Costs}} > 1`,
      solutionText: "B/C > 1 means benefits exceed costs at the given MARR.",
    },
    {
      id: "m20",
      prompt: "The marginal tax rate affects the after-tax MARR. After-tax MARR is approximately:",
      choices: ["Before-tax MARR × (1 - tax rate)", "Before-tax MARR / (1 - tax rate)", "Before-tax MARR × (1 + tax rate)", "Before-tax MARR - tax rate"],
      correctIndex: 0,
      solutionMath: String.raw`i_{\text{after-tax}} = i_{\text{before-tax}}(1 - t)`,
      solutionText: "Taxes reduce the real return required from projects.",
    },
    {
      id: "m21",
      prompt: "For a project with unequal lives, the repeatability assumption means:",
      choices: ["Both alternatives repeat until they can be compared over a common period", "We assume projects last forever", "We ignore salvage values", "We use the shortest life only"],
      correctIndex: 0,
      solutionMath: String.raw`n_{\text{study}} = \text{LCM}(n_A, n_B)`,
      solutionText: "LCM (Least Common Multiple) allows fair comparison of different-life alternatives.",
    },
    {
      id: "m22",
      prompt: "Which statement about payback period is TRUE?",
      choices: ["Ignores cash flows after payback period", "Considers time value of money (discounted payback)", "Is always the best criterion", "Guarantees maximum NPV"],
      correctIndex: 0,
      solutionText: "Simple payback ignores post-payback cash flows. Discounted payback at least considers TVM.",
    },
    {
      id: "m23",
      prompt: "In depreciation calculations (MACRS), which property class has the longest recovery period?",
      choices: ["39-year property", "7-year property", "5-year property", "3-year property"],
      correctIndex: 0,
      solutionText: "Real estate uses 39-year recovery period under MACRS.",
    },
    // True/False Questions
    {
      id: "mf01",
      type: "truefalse",
      prompt: "The IRR method always gives the same ranking as the NPW method for mutually exclusive projects.",
      correctIndex: 1,
      solutionText: "False. IRR and NPW can rank mutually exclusive projects differently due to differences in cash flow timing and scale.",
    },
    {
      id: "mf02",
      type: "truefalse",
      prompt: "Using the AW (Annual Worth) method is equivalent to using the NPW method for comparing alternatives with different lives.",
      correctIndex: 0,
      solutionMath: String.raw`AW = NPW \times (A/P, i, n)`,
      solutionText: "True. AW converts NPW to equivalent annual series, making different-life alternatives comparable.",
    },
    {
      id: "mf03",
      type: "truefalse",
      prompt: "In an arithmetic gradient, the gradient amount G first appears in Year 2.",
      correctIndex: 0,
      solutionText: "True. By convention, the arithmetic gradient starts at Period 2, not Period 1.",
    },
    {
      id: "mf04",
      type: "truefalse",
      prompt: "MACRS depreciation is based on straight-line method for most property classes.",
      correctIndex: 1,
      solutionText: "False. MACRS primarily uses accelerated depreciation methods (declining balance switching to straight-line).",
    },
    // Fill in the Blank Questions
    {
      id: "mb01",
      type: "fillblank",
      prompt: "The formula for EUAC is: EUAC = P × (A/P, i%, n) - S × (A/F, i%, n). S stands for _____ value.",
      correctAnswer: "salvage",
      solutionMath: String.raw`S = \text{Salvage Value}`,
      solutionText: "S is the salvage value or market value at the end of the useful life.",
    },
    {
      id: "mb02",
      type: "fillblank",
      prompt: "In the formula (P/G, i%, n), the letter G represents the _____ gradient amount.",
      correctAnswer: "arithmetic",
      solutionMath: String.raw`G = \text{Arithmetic Gradient}`,
      solutionText: "G is the arithmetic (linear) gradient amount - the constant increment each period.",
    },
    {
      id: "mb03",
      type: "fillblank",
      prompt: "If the benefit-cost ratio (B/C) is greater than _____, the project is economically justified.",
      correctAnswer: "1",
      solutionText: "B/C > 1 means benefits exceed costs at the given discount rate.",
    },
    {
      id: "mb04",
      type: "fillblank",
      prompt: "The weighted average cost of capital (WACC) is typically used as the _____ for project evaluation.",
      correctAnswer: "discount rate",
      solutionText: "WACC represents the required return that should be used to discount project cash flows.",
    },
  ],
  hard: [
    {
      id: "h01",
      prompt: "Loan A: 9.0% nominal compounded daily (365). Loan B: 9.2% nominal compounded annually. For borrowing cost measured by EAR, choose:",
      choices: ["B is cheaper (lower EAR)", "A is cheaper", "Same EAR", "Cannot compare"],
      correctIndex: 0,
      solutionMath: String.raw`i_{aA}=\left(1+\frac{0.09}{365}\right)^{365}-1\approx 9.42\%,\quad i_{aB}=9.20\%`,
      solutionText: "Daily compounding pushes A’s effective rate above its nominal headline; B’s EAR equals 9.2% with annual compounding.",
    },
    {
      id: "h02",
      prompt: "A five-year investment has NCF: -5000 at t=0, +1200 for t=1..5, +500 salvage at t=5. At i=10%, NPW uses which pattern?",
      choices: [
        "NPW = -5000 + 1200(P/A,10%,5) + 500(P/F,10%,5)",
        "NPW ignores salvage always",
        "NPW uses (F/A) only",
        "NPW uses simple interest",
      ],
      correctIndex: 0,
      solutionMath: String.raw`\mathrm{NPW}=-5000+1200(P/A,10\%,5)+500(P/F,10\%,5)`,
      solutionText: "Break the pattern into a uniform series plus a single future receipt at the horizon.",
    },
    {
      id: "h03",
      prompt: "Two mutually exclusive machines: A has NPW = $4,000; B has NPW = $4,800 at the same MARR and same study period. Choose:",
      choices: ["B", "A", "Neither", "Flip a coin"],
      correctIndex: 0,
      solutionMath: String.raw`\max\{\mathrm{NPW}_A,\mathrm{NPW}_B\}`,
      solutionText: "Higher NPW wins among feasible mutually exclusive options under consistent assumptions.",
    },
    {
      id: "h04",
      prompt: "Effective rate for 5% nominal compounded semiannually (one year) is:",
      choices: ["5.0625%", "5.0000%", "10.0000%", "2.5000%"],
      correctIndex: 0,
      solutionMath: String.raw`i_a=(1+0.05/2)^2-1=1.025^2-1=0.050625`,
      solutionText: "Two compounding periods at 2.5% each: interest-on-interest within the year lifts the effective annual rate slightly above 5%.",
    },
    {
      id: "h05",
      prompt: "Capitalized cost idea: for infinite renewals with repeating first cost C0 and perpetual annual cost A, analysis often uses:",
      choices: [
        "PW of perpetual maintenance plus cycleized replacement logic (text-dependent)",
        "Only payback period",
        "Only simple interest",
        "IRR without cash flows",
      ],
      correctIndex: 0,
      solutionMath: String.raw`P_{\infty}=\frac{A}{i}+\text{(replacement cycle terms as modeled)}`,
      solutionText: "Capitalized-cost methods combine perpetuity formulas with replacement assumptions; follow your text’s template for repeated renewals.",
    },
    {
      id: "h06",
      prompt: "If NPW(i) is strictly decreasing in i for a conventional project, the IRR i* satisfies:",
      choices: ["NPW(i*) = 0 (by definition of IRR for that pattern)", "NPW always increases with i", "IRR equals MARR always", "NPW is unrelated to IRR"],
      correctIndex: 0,
      solutionMath: String.raw`0=\sum_t \frac{NCF_t}{(1+i^*)^t}`,
      solutionText: "IRR is the rate that zeros the NPW function; ranking by IRR across mutually exclusive projects can conflict with NPW unless careful.",
    },
    {
      id: "h07",
      prompt: "Find n from F and P: F = P(1+i)^n ⇒ n equals:",
      choices: ["ln(F/P) / ln(1+i)", "(F-P)/i", "F/P", "P/F"],
      correctIndex: 0,
      solutionMath: String.raw`n=\frac{\ln(F/P)}{\ln(1+i)}`,
      solutionText: "Take logs after dividing by P; useful for solving for doubling time or payback-like targets under compound interest.",
    },
    {
      id: "h08",
      prompt: "Geometric series check: (1+i)^n grows:",
      choices: ["Exponentially in n for fixed i>0", "Linearly always", "Constantly", "Decreasing for i>0"],
      correctIndex: 0,
      solutionMath: String.raw`(1+i)^n \text{ is exponential in } n`,
      solutionText: "This is why compound wealth curves bend upward versus simple-interest straight-line patterns over time.",
    },
    {
      id: "h09",
      prompt: "Annuity due vs ordinary annuity: the ordinary (end-of-period) annuity present worth factor (P/A,i,n) assumes the first A occurs at:",
      choices: ["t = 1 (end of first period)", "t = 0", "t = n only", "t = -1"],
      correctIndex: 0,
      solutionMath: String.raw`P=A(P/A,i,n)\ \text{with first }A\text{ at period 1}`,
      solutionText: "If cash flows begin at t=0, adjust with an (F/P) or time-shift trick per textbook convention.",
    },
    {
      id: "h10",
      prompt: "Short project: -100 at t=0, +60 at t=1, +70 at t=2. At i=10%, NPW is about:",
      choices: ["+9.75", "-20.00", "0.00", "-5.50"],
      correctIndex: 0,
      solutionMath: String.raw`\mathrm{NPW}=-100+60(1.1)^{-1}+70(1.1)^{-2}`,
      solutionText: "Discount each net cash flow: 60/1.1 + 70/1.21 − 100 ≈ 9.75.",
    },
    {
      id: "h11",
      prompt: "When comparing alternatives with different lives without aligning horizons, NPW can be misleading because:",
      choices: [
        "The study period and replacement assumptions are inconsistent",
        "MARR must be zero",
        "Salvage must be ignored",
        "Interest rates do not matter",
      ],
      correctIndex: 0,
      solutionMath: String.raw`\text{NPW requires consistent } n_{\text{study}}`,
      solutionText: "Different lives require an explicit common horizon (LCM approach, stated horizon, or equivalent annual worth methods).",
    },
    {
      id: "h12",
      prompt: "If continuous compounding uses F = Pe^{rt}, then the effective annual factor for one year (t=1) relative to P is:",
      choices: ["e^{r}", "r", "1+r", "ln(r)"],
      correctIndex: 0,
      solutionMath: String.raw`F/P=e^{r}`,
      solutionText: "Over one year, wealth scales by e^{r} under continuous compounding at continuous rate r (verify notation vs nominal forms).",
    },
    {
      id: "h13",
      prompt: "For a lease with payments at the beginning of each period (annuity due), the present worth factor is:",
      choices: ["(P/A, i%, n) × (1+i)", "(P/A, i%, n)", "(P/A, i%, n) / (1+i)", "(F/A, i%, n)"],
      correctIndex: 0,
      solutionMath: String.raw`(P/A)_{\text{due}} = (P/A, i, n)(1+i)`,
      solutionText: "Annuity due payments start immediately, so they accumulate interest for one extra period.",
    },
    {
      id: "h14",
      prompt: "The IRR of a project with cash flows: -1000, +600, +600 is closest to:",
      choices: ["21%", "15%", "30%", "10%"],
      correctIndex: 0,
      solutionMath: String.raw`0 = -1000 + 600/(1+IRR) + 600/(1+IRR)^2`,
      solutionText: "Solve for IRR: approximately 21% (NPV = 0 at this rate).",
    },
    {
      id: "h15",
      prompt: "In sensitivity analysis, a project with NPV most sensitive to sales volume means:",
      choices: ["Small change in volume causes large NPV change", "Volume doesn't affect NPV", "Fixed costs dominate", "Revenue has no impact"],
      correctIndex: 0,
      solutionMath: String.raw`\text{Sensitivity} = \frac{\Delta NPV / NPV}{\Delta Volume / Volume}`,
      solutionText: "Higher sensitivity means more risk if volume estimates are uncertain.",
    },
    {
      id: "h16",
      prompt: "For mutually exclusive projects with unequal lives, using AW (Annual Worth) method means:",
      choices: ["Choose the one with higher AW", "Choose the one with higher NPV", "Choose the shorter life always", "Choose the one with higher IRR"],
      correctIndex: 0,
      solutionMath: String.raw`AW = NPW \times (A/P, i, n)`,
      solutionText: "Annual Worth converts NPV to equivalent annual series, allowing fair comparison of different lives.",
    },
    {
      id: "h17",
      prompt: "The internal rate of return (IRR) may not exist for a project with:",
      choices: ["Non-conventional cash flows (sign changes more than once)", "All positive cash flows", "Initial investment only", "Uniform cash flows"],
      correctIndex: 0,
      solutionMath: String.raw`\sum_{t=0}^n \frac{NCF_t}{(1+IRR)^t} = 0`,
      solutionText: "Multiple sign changes can produce multiple IRRs or no real IRR.",
    },
    {
      id: "h18",
      prompt: "In a replacement analysis, the defender's current market value is:",
      choices: ["What you can sell it for TODAY", "Its original cost minus depreciation", "Its book value", "Its future salvage value"],
      correctIndex: 0,
      solutionMath: String.raw`MV_{\text{defender}} = \text{Current market value}`,
      solutionText: "Sunk cost principle: only current market value matters for go/no-go decision.",
    },
    {
      id: "h19",
      prompt: "For a bond with yield to maturity (YTM) of 8% and coupon rate of 6%, the bond trades at:",
      choices: ["A discount (below par)", "At par (face value)", "At a premium (above par)", "Cannot determine"],
      correctIndex: 0,
      solutionMath: String.raw`\text{If YTM > Coupon Rate } \Rightarrow \text{ Discount}`,
      solutionText: "When market required return exceeds the coupon rate, investors demand a lower price.",
    },
    {
      id: "h20",
      prompt: "In inflation-adjusted analysis, the real interest rate approximately equals:",
      choices: ["(1+nominal)/(1+inflation) - 1", "Nominal rate minus inflation rate", "Inflation rate minus nominal rate", "Nominal rate plus inflation rate"],
      correctIndex: 0,
      solutionMath: String.raw`i_{\text{real}} = \frac{1 + i_{\text{nominal}}}{1 + f} - 1`,
      solutionText: "Fisher equation: approximate real rate = nominal - inflation; exact uses product formula.",
    },
    {
      id: "h21",
      prompt: "For a project with financing costs in cash flows, the weighted average cost of capital (WACC) is used as:",
      choices: ["The discount rate for all project cash flows", "Only for the initial investment", "Only for terminal year cash flows", "Not relevant for project evaluation"],
      correctIndex: 0,
      solutionMath: String.raw`NPW = \sum_{t=0}^n \frac{CF_t}{(1+WACC)^t}`,
      solutionText: "WACC reflects both debt and equity financing costs; use consistently throughout analysis.",
    },
    {
      id: "h22",
      prompt: "The depreciation tax shield in after-tax analysis equals:",
      choices: ["Depreciation × Tax rate", "Depreciation / Tax rate", "Book value × Tax rate", "None of the above"],
      correctIndex: 0,
      solutionMath: String.raw`DTS = D \times t`,
      solutionText: "Depreciation reduces taxable income, creating a tax savings equal to D × t.",
    },
    {
      id: "h23",
      prompt: "In a lease vs. buy decision, from the lessee's perspective, the after-tax cost of leasing is compared to:",
      choices: ["After-tax cost of buying", "Before-tax cost of buying", "Purchase price only", "Operating costs only"],
      correctIndex: 0,
      solutionMath: String.raw`ATCL = PCL \times (1 - t)`,
      solutionText: "Lease payments are typically tax-deductible, reducing their effective cost.",
    },
    // True/False Questions
    {
      id: "hf01",
      type: "truefalse",
      prompt: "A project can have multiple IRRs if it has non-conventional cash flows (multiple sign changes).",
      correctIndex: 0,
      solutionText: "True. Cash flows with multiple sign changes can produce multiple IRR solutions.",
    },
    {
      id: "hf02",
      type: "truefalse",
      prompt: "In a replacement analysis, the defender's book value should be used as the investment cost for the challenger analysis.",
      correctIndex: 1,
      solutionText: "False. Always use current market value, not book value. Book value is a sunk cost.",
    },
    {
      id: "hf03",
      type: "truefalse",
      prompt: "The exact Fisher equation for real interest rate is: i_real = i_nominal - f (inflation rate).",
      correctIndex: 1,
      solutionMath: String.raw`i_{\text{real}} = \frac{1 + i_{\text{nominal}}}{1 + f} - 1`,
      solutionText: "False. The approximate formula is i_real ≈ i_nominal - f, but the exact formula is i_real = (1+i_nominal)/(1+f) - 1.",
    },
    {
      id: "hf04",
      type: "truefalse",
      prompt: "In after-tax analysis, the depreciation tax shield is more valuable at higher tax rates.",
      correctIndex: 0,
      solutionText: "True. Depreciation tax shield = D × t, so higher tax rate means larger tax savings.",
    },
    // Fill in the Blank Questions
    {
      id: "hb01",
      type: "fillblank",
      prompt: "The formula for modified IRR (MIRR) uses the finance rate for negative cash flows and the _____ rate for positive cash flows.",
      correctAnswer: "reinvestment",
      solutionMath: String.raw`\text{MIRR uses both finance and reinvestment rates}`,
      solutionText: "MIRR assumes negative cash flows are financed at the finance rate and positive cash flows are reinvested at the reinvestment rate.",
    },
    {
      id: "hb02",
      type: "fillblank",
      prompt: "In capital budgeting, the hurdle rate is typically set equal to the _____ cost of capital.",
      correctAnswer: "weighted average",
      solutionMath: String.raw`\text{Hurdle Rate} = WACC`,
      solutionText: "The hurdle rate (MARR) is usually set equal to or slightly above the WACC.",
    },
    {
      id: "hb03",
      type: "fillblank",
      prompt: "When evaluating mutually exclusive projects with different lives, the _____ worth method automatically accounts for different life spans.",
      correctAnswer: "annual",
      solutionMath: String.raw`AW = NPW \times (A/P, i, n)`,
      solutionText: "The Annual Worth (AW) method converts NPV to equivalent annual cash flows, allowing fair comparison.",
    },
    {
      id: "hb04",
      type: "fillblank",
      prompt: "The internal rate of return (IRR) solves for the discount rate where NPV = _____.",
      correctAnswer: "0",
      solutionMath: String.raw`0 = \sum_{t=0}^n \frac{NCF_t}{(1+IRR)^t}`,
      solutionText: "IRR is the rate that makes the net present value equal to zero.",
    },
  ],
};