/**
 * Challenge bank — 12 questions per difficulty (36 total).
 * Each item: { id, prompt, promptMath?, choices[], correctIndex, solutionMath, solutionText? }
 * choices are plain text (numbers/currency) for readability; solutions use KaTeX.
 */
window.CHALLENGE_BANK = {
  easy: [
    {
      id: "e01",
      prompt: "Simple interest only on principal: I = Pin. For P = $5,000, i = 8% per year, n = 5 years, total interest is:",
      promptMath: String.raw`I = Pin`,
      choices: ["$2,000", "$1,600", "$2,500", "$700"],
      correctIndex: 0,
      solutionMath: String.raw`I = (5000)(0.08)(5) = 2000`,
      solutionText: "Simple interest does not compound: each year’s interest is 0.08·5000 = 400, so over 5 years interest totals 5·400 = 2000.",
    },
    {
      id: "e02",
      prompt: "Compound annually: F = P(1+i)^n. If P = $500, i = 6%, n = 3 years, F is closest to:",
      promptMath: String.raw`F=P(1+i)^n`,
      choices: ["$595.50", "$590.00", "$600.00", "$530.00"],
      correctIndex: 0,
      solutionMath: String.raw`F=500(1.06)^3 \approx 500(1.191016)=595.51`,
      solutionText: "Apply the single-payment compound factor once per year for three years.",
    },
    {
      id: "e03",
      prompt: "Discount a single future receipt: P = F(1+i)^{-n}. To have F = $800 in 4 years at i = 5% compounded annually, deposit now about:",
      promptMath: String.raw`P=F(1+i)^{-n}`,
      choices: ["$658.16", "$640.00", "$680.00", "$800.00"],
      correctIndex: 0,
      solutionMath: String.raw`P=800(1.05)^{-4} \approx 800(0.822702)=658.16`,
      solutionText: "Use the P/F relationship; the factor (P/F,5%,4) is 1/(F/P,5%,4).",
    },
    {
      id: "e04",
      prompt: "Nominal r = 12% compounded monthly: effective annual rate i_a = (1+r/12)^{12}-1 is approximately:",
      promptMath: String.raw`i_a=\left(1+\frac{r}{12}\right)^{12}-1`,
      choices: ["12.68%", "12.00%", "13.50%", "11.88%"],
      correctIndex: 0,
      solutionMath: String.raw`i_a=(1+0.01)^{12}-1 \approx 0.126825`,
      solutionText: "Monthly means m=12; periodic rate is 0.12/12 = 0.01 per month.",
    },
    {
      id: "e05",
      prompt: "Sinking fund style: solve for A given F. Which factor converts F to an end-of-period uniform series A?",
      choices: ["(A/F,i,n)", "(F/A,i,n)", "(P/A,i,n)", "(A/P,i,n)"],
      correctIndex: 0,
      solutionMath: String.raw`A = F(A/F,i,n)=F\cdot\frac{i}{(1+i)^n-1}`,
      solutionText: "(F/A,i,n) finds F from A; its reciprocal structure yields (A/F,i,n) for the reverse.",
    },
    {
      id: "e06",
      prompt: "End-of-period annuity future worth: F = A·[((1+i)^n-1)/i]. With A = $1,000, i = 7%, n = 4, F is closest to:",
      promptMath: String.raw`F=A\left[\frac{(1+i)^n-1}{i}\right]`,
      choices: ["$4,440", "$4,000", "$4,750", "$3,850"],
      correctIndex: 0,
      solutionMath: String.raw`F=1000\cdot\frac{1.07^4-1}{0.07}\approx 1000\cdot 4.4399`,
      solutionText: "This is the uniform-series compound amount factor applied once.",
    },
    {
      id: "e07",
      prompt: "A project at MARR = 10% has NPW = +$300. The usual accept/reject conclusion is:",
      choices: ["Accept (economically attractive at the stated MARR)", "Reject", "Accept only if payback < 2 years", "Cannot decide without IRR"],
      correctIndex: 0,
      solutionMath: String.raw`\mathrm{NPW}(i=\text{MARR})>0 \Rightarrow \text{accept conventional independent project}`,
      solutionText: "Positive NPW means the cash flow stream earns more than the MARR in present-worth terms for the study period used.",
    },
    {
      id: "e08",
      prompt: "Perpetuity (end-of-period): P = A/i. If A = $600 yearly forever and i = 5%, the capitalized present worth is:",
      promptMath: String.raw`P=\frac{A}{i}`,
      choices: ["$12,000", "$600", "$30,000", "$3,000"],
      correctIndex: 0,
      solutionMath: String.raw`P=\frac{600}{0.05}=12000`,
      solutionText: "A perpetual level payment grows without bound in the future, but its present worth is finite when i>0.",
    },
    {
      id: "e09",
      prompt: "Two mutually exclusive alternatives at the same MARR and same study period both have NPW > 0. Choose:",
      choices: ["The alternative with the larger NPW", "The alternative with the smaller NPW", "The shorter-lived alternative always", "Either; NPW cannot rank"],
      correctIndex: 0,
      solutionMath: String.raw`\max \mathrm{NPW}_j \quad \text{subject to feasibility}`,
      solutionText: "With consistent assumptions and a common horizon, NPW ranking selects the economically dominant mutually exclusive option.",
    },
    {
      id: "e10",
      prompt: "Continuous compounding for one year at continuous rate r: F = Pe^{r}. If P = $2,000 and r = 6% (continuous), F is closest to:",
      promptMath: String.raw`F=Pe^{r}`,
      choices: ["$2,123.67", "$2,120.00", "$2,000.00", "$2,600.00"],
      correctIndex: 0,
      solutionMath: String.raw`F=2000e^{0.06}\approx 2000(1.0618365)`,
      solutionText: "This is the continuous analogue to discrete compounding limits as m→∞ (notation may vary by text).",
    },
    {
      id: "e11",
      prompt: "If compounding is quarterly but cash flows occur quarterly too, the interest period rate i per quarter from nominal annual r is:",
      choices: ["r/4", "r", "r/12", "(1+r)^{1/4}-1"],
      correctIndex: 0,
      solutionMath: String.raw`i_{\text{quarter}}=\frac{r}{m},\quad m=4`,
      solutionText: "Align the periodic rate with the cash-flow period before applying factors.",
    },
    {
      id: "e12",
      prompt: "NPW sign rule (single project, conventional flows): NPW < 0 at the MARR implies:",
      choices: ["The project does not meet the MARR as a PW test", "Accept immediately", "MARR must be zero", "NPW is undefined"],
      correctIndex: 0,
      solutionMath: String.raw`\mathrm{NPW}(i=\text{MARR})<0 \Rightarrow \text{reject}`,
      solutionText: "Negative NPW means the discounted net cash flows fall short of recovering capital at the hurdle rate (for the modeled assumptions).",
    },
  ],
  medium: [
    {
      id: "m01",
      prompt: "Compare borrowing costs: Loan A is 11.8% nominal compounded monthly; Loan B is 12.0% nominal compounded quarterly. Which has the lower effective annual rate (EAR)?",
      choices: ["A (about 12.47% vs 12.55%)", "B", "They are equal", "Cannot compute without principal"],
      correctIndex: 0,
      solutionMath: String.raw`i_{aA}=(1+0.118/12)^{12}-1,\quad i_{aB}=(1+0.12/4)^4-1`,
      solutionText: "Compute each EAR: A ≈ 12.47%, B ≈ 12.55%. Lower EAR is cheaper for borrowing.",
    },
    {
      id: "m02",
      prompt: "Find P for an annuity: P = A(P/A,i,n). With A = $250, i = 8% per year, n = 10, P is closest to (use tables or compute):",
      promptMath: String.raw`P=A(P/A,8\\%,10)`,
      choices: ["$1,677.53", "$2,500.00", "$1,200.00", "$3,000.00"],
      correctIndex: 0,
      solutionMath: String.raw`P=250\cdot\frac{1-(1.08)^{-10}}{0.08}\approx 250(6.7101)`,
      solutionText: "The (P/A) factor discounts a level end-of-year series to its present equivalent.",
    },
    {
      id: "m03",
      prompt: "Find A to reach F: A = F(A/F,i,n). To accumulate F = $10,000 in 6 years at i = 6% compounded annually, uniform end-of-year deposits are about:",
      choices: ["$1,433.28", "$1,666.67", "$1,200.00", "$2,000.00"],
      correctIndex: 0,
      solutionMath: String.raw`A=10000\cdot\frac{0.06}{(1.06)^6-1}`,
      solutionText: "This is the sinking-fund factor: spread a future target into equivalent annual set-asides.",
    },
    {
      id: "m04",
      prompt: "Two-year loan effective rate: 12% nominal compounded monthly for a 6-month horizon. The 6-month effective rate is closest to:",
      choices: ["6.15%", "6.00%", "12.00%", "3.00%"],
      correctIndex: 0,
      solutionMath: String.raw`i_{6\text{-mo}}=\left(1+\frac{0.12}{12}\right)^{6}-1`,
      solutionText: "Six monthly periods at 1% per month: (1.01)^6−1 ≈ 6.15% for the half-year.",
    },
    {
      id: "m05",
      prompt: "Given P = $1,000, i = 8% per year, n = 5 annual periods, F = P(F/P,8%,5). F is closest to:",
      choices: ["$1,469.33", "$1,400.00", "$1,800.00", "$1,080.00"],
      correctIndex: 0,
      solutionMath: String.raw`F=1000(1.08)^5 \approx 1469.33`,
      solutionText: "Single-payment compound amount for five annual periods.",
    },
    {
      id: "m06",
      prompt: "If a project’s NPW at MARR is exactly zero, the interpretation is:",
      choices: ["The project returns exactly the MARR in PW terms", "The project loses money for sure", "IRR is undefined", "MARR must be negative"],
      correctIndex: 0,
      solutionMath: String.raw`\mathrm{NPW}(i=i^*)=0 \Rightarrow i^*=\text{IRR for simple cases}`,
      solutionText: "NPW = 0 means the discounted cash flows break even against the hurdle rate used in the analysis.",
    },
    {
      id: "m07",
      prompt: "Different-life machines with repeatability: the study period is often chosen as:",
      choices: ["The LCM of useful lives", "Always 1 year", "The longer life only", "The shorter life only"],
      correctIndex: 0,
      solutionMath: String.raw`n_{\text{study}}=\mathrm{lcm}(n_A,n_B)`,
      solutionText: "Align repeated cycles so each alternative experiences an integer number of replacements over the same horizon.",
    },
    {
      id: "m08",
      prompt: "Arithmetic gradient base+G pattern: the standard tabulated (P/G,i,n) factor applies to a series that begins with:",
      choices: ["0 at period 1, then G,2G,… after converting the base", "A positive cash flow at period 0 only", "Equal amounts forever without base", "Only decreasing series"],
      correctIndex: 0,
      solutionMath: String.raw`P = A(P/A,i,n) \pm G(P/G,i,n)`,
      solutionText: "Textbooks shift the standard gradient form; always match the tabulated convention to your cash-flow timing.",
    },
    {
      id: "m09",
      prompt: "Continuous effective annual rate from continuous nominal r (common textbook form): i_a equals:",
      choices: ["e^{r}-1", "r", "ln(1+r)", "e^{r}"],
      correctIndex: 0,
      solutionMath: String.raw`i_a=e^r-1`,
      solutionText: "This pairs with F = Pe^{rt} for continuous compounding over t years (verify notation in your 11th edition).",
    },
    {
      id: "m10",
      prompt: "You need F = $2,000 in 3 years. Bank pays 3% compounded annually. Deposit today P is about:",
      choices: ["$1,827.07", "$2,000.00", "$1,940.00", "$1,700.00"],
      correctIndex: 0,
      solutionMath: String.raw`P=2000(1.03)^{-3}`,
      solutionText: "Single-payment present worth factor applied once.",
    },
    {
      id: "m11",
      prompt: "For mutually exclusive alternatives with different lives, comparing NPW at each asset’s own life without adjustment generally:",
      choices: ["Can mis-rank unless study periods are aligned", "Is always correct", "Requires IRR only", "Ignores salvage automatically"],
      correctIndex: 0,
      solutionMath: String.raw`\text{Need consistent } n_{\text{study}} \text{ and replacement assumptions}`,
      solutionText: "NPW comparisons must use the same analysis window and consistent reinvestment assumptions.",
    },
    {
      id: "m12",
      prompt: "If compounding is monthly but deposits are end-of-month, the correct periodic i in monthly factors is typically:",
      choices: ["Nominal annual rate divided by 12", "Nominal annual rate", "EAR divided by 12 without checking", "Zero"],
      correctIndex: 0,
      solutionMath: String.raw`i_{\text{month}}=\frac{r}{12}`,
      solutionText: "Match i and n to the month; then use (F/A,i,n) with n in months.",
    },
  ],
  hard: [
    {
      id: "h01",
      prompt: "Loan A: 9.0% nominal compounded daily (365). Loan B: 9.2% nominal compounded annually. For borrowing cost measured by EAR, choose:",
      choices: ["B is cheaper (lower EAR)", "A is cheaper", "Same EAR", "Cannot compare"],
      correctIndex: 0,
      solutionMath: String.raw`i_{aA}=\left(1+\frac{0.09}{365}\right)^{365}-1\approx 9.42\\%,\quad i_{aB}=9.20\\%`,
      solutionText: "Daily compounding pushes A’s effective rate above its nominal headline; B’s EAR equals 9.2% with annual compounding.",
    },
    {
      id: "h02",
      prompt: "A five-year investment has NCF: -5000 at t=0, +1200 for t=1..5, +500 salvage at t=5. At i=10%, NPW uses which pattern?",
      choices: [
        "NPW = -5000 + 1200(P/A,10%,5) + 500(P/F,10%,5)",
        "NPW ignores salvage always",
        "NPW uses (F/A) only",
        "NPW uses simple interest",
      ],
      correctIndex: 0,
      solutionMath: String.raw`\mathrm{NPW}=-5000+1200(P/A,10\\%,5)+500(P/F,10\\%,5)`,
      solutionText: "Break the pattern into a uniform series plus a single future receipt at the horizon.",
    },
    {
      id: "h03",
      prompt: "Two mutually exclusive machines: A has NPW = $4,000; B has NPW = $4,800 at the same MARR and same study period. Choose:",
      choices: ["B", "A", "Neither", "Flip a coin"],
      correctIndex: 0,
      solutionMath: String.raw`\max\{\mathrm{NPW}_A,\mathrm{NPW}_B\}`,
      solutionText: "Higher NPW wins among feasible mutually exclusive options under consistent assumptions.",
    },
    {
      id: "h04",
      prompt: "Effective rate for 5% nominal compounded semiannually (one year) is:",
      choices: ["5.0625%", "5.0000%", "10.0000%", "2.5000%"],
      correctIndex: 0,
      solutionMath: String.raw`i_a=(1+0.05/2)^2-1=1.025^2-1=0.050625`,
      solutionText: "Two compounding periods at 2.5% each: interest-on-interest within the year lifts the effective annual rate slightly above 5%.",
    },
    {
      id: "h05",
      prompt: "Capitalized cost idea: for infinite renewals with repeating first cost C0 and perpetual annual cost A, analysis often uses:",
      choices: [
        "PW of perpetual maintenance plus cycleized replacement logic (text-dependent)",
        "Only payback period",
        "Only simple interest",
        "IRR without cash flows",
      ],
      correctIndex: 0,
      solutionMath: String.raw`P_{\infty}=\frac{A}{i}+\text{(replacement cycle terms as modeled)}`,
      solutionText: "Capitalized-cost methods combine perpetuity formulas with replacement assumptions; follow your text’s template for repeated renewals.",
    },
    {
      id: "h06",
      prompt: "If NPW(i) is strictly decreasing in i for a conventional project, the IRR i* satisfies:",
      choices: ["NPW(i*) = 0 (by definition of IRR for that pattern)", "NPW always increases with i", "IRR equals MARR always", "NPW is unrelated to IRR"],
      correctIndex: 0,
      solutionMath: String.raw`0=\sum_t \frac{NCF_t}{(1+i^*)^t}`,
      solutionText: "IRR is the rate that zeros the NPW function; ranking by IRR across mutually exclusive projects can conflict with NPW unless careful.",
    },
    {
      id: "h07",
      prompt: "Find n from F and P: F = P(1+i)^n ⇒ n equals:",
      choices: ["ln(F/P) / ln(1+i)", "(F-P)/i", "F/P", "P/F"],
      correctIndex: 0,
      solutionMath: String.raw`n=\frac{\ln(F/P)}{\ln(1+i)}`,
      solutionText: "Take logs after dividing by P; useful for solving for doubling time or payback-like targets under compound interest.",
    },
    {
      id: "h08",
      prompt: "Geometric series check: (1+i)^n grows:",
      choices: ["Exponentially in n for fixed i>0", "Linearly always", "Constantly", "Decreasing for i>0"],
      correctIndex: 0,
      solutionMath: String.raw`(1+i)^n \text{ is exponential in } n`,
      solutionText: "This is why compound wealth curves bend upward versus simple-interest straight-line patterns over time.",
    },
    {
      id: "h09",
      prompt: "Annuity due vs ordinary annuity: the ordinary (end-of-period) annuity present worth factor (P/A,i,n) assumes the first A occurs at:",
      choices: ["t = 1 (end of first period)", "t = 0", "t = n only", "t = -1"],
      correctIndex: 0,
      solutionMath: String.raw`P=A(P/A,i,n)\ \text{with first }A\text{ at period 1}`,
      solutionText: "If cash flows begin at t=0, adjust with an (F/P) or time-shift trick per textbook convention.",
    },
    {
      id: "h10",
      prompt: "Short project: -100 at t=0, +60 at t=1, +70 at t=2. At i=10%, NPW is about:",
      choices: ["+9.75", "-20.00", "0.00", "-5.50"],
      correctIndex: 0,
      solutionMath: String.raw`\mathrm{NPW}=-100+60(1.1)^{-1}+70(1.1)^{-2}`,
      solutionText: "Discount each net cash flow: 60/1.1 + 70/1.21 − 100 ≈ 9.75.",
    },
    {
      id: "h11",
      prompt: "When comparing alternatives with different lives without aligning horizons, NPW can be misleading because:",
      choices: [
        "The study period and replacement assumptions are inconsistent",
        "MARR must be zero",
        "Salvage must be ignored",
        "Interest rates do not matter",
      ],
      correctIndex: 0,
      solutionMath: String.raw`\text{NPW requires consistent } n_{\text{study}}`,
      solutionText: "Different lives require an explicit common horizon (LCM approach, stated horizon, or equivalent annual worth methods).",
    },
    {
      id: "h12",
      prompt: "If continuous compounding uses F = Pe^{rt}, then the effective annual factor for one year (t=1) relative to P is:",
      choices: ["e^{r}", "r", "1+r", "ln(r)"],
      correctIndex: 0,
      solutionMath: String.raw`F/P=e^{r}`,
      solutionText: "Over one year, wealth scales by e^{r} under continuous compounding at continuous rate r (verify notation vs nominal forms).",
    },
  ],
};